framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto  # ou false si tu veux forcer sans HTTPS
        cookie_samesite: lax


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
